<?xml version="1.0" encoding="utf-8"?><Database Name="News" Class="NewsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Accouts" Member="Accouts">
    <Type Name="Accout">
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Fullname" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Permission" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Lock" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Info" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Avata" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="Accout_Menus" Member="Menus" ThisKey="UserName" OtherKey="UserAdd" Type="Menus" />
    </Type>
  </Table>
  <Table Name="dbo.Menu_Footer" Member="Menu_Footers">
    <Type Name="Menu_Footer">
      <Column Name="ID_Footer" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ParentID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Link" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TitleFooter" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="Menu_Footer_PageFooter" Member="PageFooters" ThisKey="ID_Footer" OtherKey="ID_Footer" Type="PageFooter" />
    </Type>
  </Table>
  <Table Name="dbo.Menus" Member="Menus">
    <Type Name="Menus">
      <Column Name="ID_MN" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Parent" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Pos" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Lablel" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="UrlLink" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="OrderKey" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="UserAdd" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserText" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Hide" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Menus_PageItem" Member="PageItems" ThisKey="ID_MN" OtherKey="ID_MN" Type="PageItem" />
      <Association Name="Accout_Menus" Member="Accout" ThisKey="UserAdd" OtherKey="UserName" Type="Accout" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PageFooter" Member="PageFooters">
    <Type Name="PageFooter">
      <Column Name="ID_F" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_Footer" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ContentF" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TitleF" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="Menu_Footer_PageFooter" Member="Menu_Footer" ThisKey="ID_Footer" OtherKey="ID_Footer" Type="Menu_Footer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PageItems" Member="PageItems">
    <Type Name="PageItem">
      <Column Name="ID_P" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_MN" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Sumary" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Contents" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CreaDate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModiDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="OrderKey" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="UserAdd" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserText" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Hide" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="Menus_PageItem" Member="Menus" ThisKey="ID_MN" OtherKey="ID_MN" Type="Menus" IsForeignKey="true" />
    </Type>
  </Table>
</Database>